### ISSUE TITLE
Local run fails to connect to service endpoint

### ISSUE THREAD

**Issue by iwb-gmougenel** [jnshubham/aws-glue-local-etl-docker#3]
Hello, I got this issue while running a script from the docker container :

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/glue/aws-glue-libs/jarsv1/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/glue/spark-2.4.3-bin-spark-2.4.3-bin-hadoop2.8/jars/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
20/07/29 13:20:19 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
20/07/29 13:20:20 INFO SparkContext: Running Spark version 2.4.3
20/07/29 13:20:20 INFO SparkContext: Submitted application: adcampaign.py
20/07/29 13:20:20 INFO SecurityManager: Changing view acls to: root
20/07/29 13:20:20 INFO SecurityManager: Changing modify acls to: root
20/07/29 13:20:20 INFO SecurityManager: Changing view acls groups to: 
20/07/29 13:20:20 INFO SecurityManager: Changing modify acls groups to: 
20/07/29 13:20:20 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(root); groups with view permissions: Set(); users  with modify permissions: Set(root); groups with modify permissions: Set()
20/07/29 13:20:20 INFO Utils: Successfully started service 'sparkDriver' on port 37777.
20/07/29 13:20:20 INFO SparkEnv: Registering MapOutputTracker
20/07/29 13:20:20 INFO SparkEnv: Registering BlockManagerMaster
20/07/29 13:20:20 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
20/07/29 13:20:20 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
20/07/29 13:20:20 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-662d3ccc-b0a0-484e-b2c8-c19489d82dee
20/07/29 13:20:20 INFO MemoryStore: MemoryStore started with capacity 366.3 MB
20/07/29 13:20:21 INFO SparkEnv: Registering OutputCommitCoordinator
20/07/29 13:20:21 INFO Utils: Successfully started service 'SparkUI' on port 4040.
20/07/29 13:20:21 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://c2d41403de97:4040
20/07/29 13:20:21 INFO SparkContext: Added file file:///glue/aws-glue-libs/PyGlue.zip at file:///glue/aws-glue-libs/PyGlue.zip with timestamp 1596028821321
20/07/29 13:20:21 INFO Utils: Copying /glue/aws-glue-libs/PyGlue.zip to /tmp/spark-bab4c315-b173-49ec-aaac-aa428762d391/userFiles-5029a574-4857-4bdd-80b6-82c4e4ab9824/PyGlue.zip
20/07/29 13:20:21 INFO Executor: Starting executor ID driver on host localhost
20/07/29 13:20:21 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 40451.
20/07/29 13:20:21 INFO NettyBlockTransferService: Server created on c2d41403de97:40451
20/07/29 13:20:21 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
20/07/29 13:20:21 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, c2d41403de97, 40451, None)
20/07/29 13:20:21 INFO BlockManagerMasterEndpoint: Registering block manager c2d41403de97:40451 with 366.3 MB RAM, BlockManagerId(driver, c2d41403de97, 40451, None)
20/07/29 13:20:21 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, c2d41403de97, 40451, None)
20/07/29 13:20:21 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, c2d41403de97, 40451, None)
20/07/29 13:20:21 INFO GlueContext: GlueMetrics not configured
20/07/29 13:20:21 INFO GlueContext: fs.s3.impl hadoop configuration is not set. Setting fs.s3.impl to org.apache.hadoop.fs.s3a.S3AFileSystem
20/07/29 13:20:30 WARN EC2MetadataUtils: Unable to retrieve the requested metadata (/latest/dynamic/instance-identity/document). Failed to connect to service endpoint: 
com.amazonaws.SdkClientException: Failed to connect to service endpoint: 
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:100)
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:70)
	at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.readResource(InstanceMetadataServiceResourceFetcher.java:75)
	at com.amazonaws.internal.EC2ResourceFetcher.readResource(EC2ResourceFetcher.java:66)
	at com.amazonaws.util.EC2MetadataUtils.getItems(EC2MetadataUtils.java:402)
	at com.amazonaws.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:371)
	at com.amazonaws.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:367)
	at com.amazonaws.util.EC2MetadataUtils.getEC2InstanceRegion(EC2MetadataUtils.java:282)
	at com.amazonaws.regions.InstanceMetadataRegionProvider.tryDetectRegion(InstanceMetadataRegionProvider.java:59)
	at com.amazonaws.regions.InstanceMetadataRegionProvider.getRegion(InstanceMetadataRegionProvider.java:50)
	at com.amazonaws.regions.AwsRegionProviderChain.getRegion(AwsRegionProviderChain.java:46)
	at com.amazonaws.services.glue.util.EndpointConfig$.getConfig(EndpointConfig.scala:42)
	at com.amazonaws.services.glue.util.Job$.init(Job.scala:75)
	at com.amazonaws.services.glue.util.Job.init(Job.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1593)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:82)
	... 24 more
Traceback (most recent call last):
  File "/glue/adcampaign.py", line 14, in <module>
    job.init(args['JOB_NAME'], args)
  File "/glue/aws-glue-libs/PyGlue.zip/awsglue/job.py", line 38, in init
  File "/glue/spark-2.4.3-bin-spark-2.4.3-bin-hadoop2.8/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/glue/spark-2.4.3-bin-spark-2.4.3-bin-hadoop2.8/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/glue/spark-2.4.3-bin-spark-2.4.3-bin-hadoop2.8/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling z:com.amazonaws.services.glue.util.Job.init.
: com.amazonaws.SdkClientException: Unable to load region information from any provider in the chain
	at com.amazonaws.regions.AwsRegionProviderChain.getRegion(AwsRegionProviderChain.java:59)
	at com.amazonaws.services.glue.util.EndpointConfig$.getConfig(EndpointConfig.scala:42)
	at com.amazonaws.services.glue.util.Job$.init(Job.scala:75)
	at com.amazonaws.services.glue.util.Job.init(Job.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

20/07/29 13:20:30 INFO SparkContext: Invoking stop() from shutdown hook
20/07/29 13:20:30 INFO SparkUI: Stopped Spark web UI at http://c2d41403de97:4040
20/07/29 13:20:30 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
20/07/29 13:20:30 INFO MemoryStore: MemoryStore cleared
20/07/29 13:20:30 INFO BlockManager: BlockManager stopped
20/07/29 13:20:30 INFO BlockManagerMaster: BlockManagerMaster stopped
20/07/29 13:20:30 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
20/07/29 13:20:30 INFO SparkContext: Successfully stopped SparkContext
20/07/29 13:20:30 INFO ShutdownHookManager: Shutdown hook called
20/07/29 13:20:30 INFO ShutdownHookManager: Deleting directory /tmp/spark-bab4c315-b173-49ec-aaac-aa428762d391
20/07/29 13:20:30 INFO ShutdownHookManager: Deleting directory /tmp/spark-bab4c315-b173-49ec-aaac-aa428762d391/pyspark-6ecdc238-8d4b-4c40-aa02-482fbcb4980b
20/07/29 13:20:30 INFO ShutdownHookManager: Deleting directory /tmp/spark-a91bdeb5-3163-499d-a70e-267bbc28adc1
```

Seems like it tries to fetch some data as if it has been run from an EC2 ?

**Comment by jnshubham** [comment]
Thanks for highlighting this, it is caused because no credentials are setup in the docker env. Just do the following 

Once inside the docker container, try setting region export AWS_REGION=us-east-1

I will be working on the fix and soon update the image.

THe error is 

```
Unable to load region information from any provider in the chain
```
and it is because it requires a default region to run.
